version: '3'

services:
  proxy:
    image: url-shortener-envoy:latest
    ports:
      - 9090:9090
    networks:
      - url-shortener

  server:
    image: url-shortener-server:latest
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - url-shortener

networks:
  url-shortener:
