// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/indrasaputra/url-shortener/proto/indrasaputra/shortener/v1 (interfaces: URLShortenerService_GetAllURLServer)

// Package mock_grpc is a generated GoMock package.
package mock_grpc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	metadata "google.golang.org/grpc/metadata"

	shortenerv1 "github.com/indrasaputra/url-shortener/proto/indrasaputra/shortener/v1"
)

// MockURLShortenerService_GetAllURLServer is a mock of URLShortenerService_GetAllURLServer interface
type MockURLShortenerService_GetAllURLServer struct {
	ctrl     *gomock.Controller
	recorder *MockURLShortenerService_GetAllURLServerMockRecorder
}

// MockURLShortenerService_GetAllURLServerMockRecorder is the mock recorder for MockURLShortenerService_GetAllURLServer
type MockURLShortenerService_GetAllURLServerMockRecorder struct {
	mock *MockURLShortenerService_GetAllURLServer
}

// NewMockURLShortenerService_GetAllURLServer creates a new mock instance
func NewMockURLShortenerService_GetAllURLServer(ctrl *gomock.Controller) *MockURLShortenerService_GetAllURLServer {
	mock := &MockURLShortenerService_GetAllURLServer{ctrl: ctrl}
	mock.recorder = &MockURLShortenerService_GetAllURLServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockURLShortenerService_GetAllURLServer) EXPECT() *MockURLShortenerService_GetAllURLServerMockRecorder {
	return m.recorder
}

// Context mocks base method
func (m *MockURLShortenerService_GetAllURLServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockURLShortenerService_GetAllURLServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockURLShortenerService_GetAllURLServer)(nil).Context))
}

// RecvMsg mocks base method
func (m *MockURLShortenerService_GetAllURLServer) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockURLShortenerService_GetAllURLServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockURLShortenerService_GetAllURLServer)(nil).RecvMsg), arg0)
}

// Send mocks base method
func (m *MockURLShortenerService_GetAllURLServer) Send(arg0 *shortenerv1.GetAllURLResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send
func (mr *MockURLShortenerService_GetAllURLServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockURLShortenerService_GetAllURLServer)(nil).Send), arg0)
}

// SendHeader mocks base method
func (m *MockURLShortenerService_GetAllURLServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader
func (mr *MockURLShortenerService_GetAllURLServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockURLShortenerService_GetAllURLServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method
func (m *MockURLShortenerService_GetAllURLServer) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockURLShortenerService_GetAllURLServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockURLShortenerService_GetAllURLServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method
func (m *MockURLShortenerService_GetAllURLServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader
func (mr *MockURLShortenerService_GetAllURLServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockURLShortenerService_GetAllURLServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method
func (m *MockURLShortenerService_GetAllURLServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer
func (mr *MockURLShortenerService_GetAllURLServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockURLShortenerService_GetAllURLServer)(nil).SetTrailer), arg0)
}
